on: [issues, pull_request]

jobs:
  ci_info_job:
    runs-on: ubuntu-latest
    name: Populate CI info
    steps:
    - name: CI info step
      id: ci-info
      uses: LLNL/radiuss-ci-info-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
